#!/bin/bash
set -ex
DATE=2022-09-01
export INPUT=data/${DATE}-rewards.csv
npx ts-node src/distribute.ts |tee logs/log-${DATE}-rewards.txt
npx ts-node src/check.ts &> logs/log-${DATE}-check.txt
grep --after=2 fail logs/log-${DATE}-check.txt |grep -v "\[" > logs/${DATE}-todo-check.txt